# Generated by Django 4.1.7 on 2023-03-03 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professorapp', '0001_initial'),
        ('Authapp', '0010_customuser_groups_customuser_user_permissions'),
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentapp.task'),
        ),
        migrations.AddField(
            model_name='bid',
            name='bided_by',
            field=models.ManyToManyField(to='Authapp.professor'),
        ),
        migrations.AddField(
            model_name='bid',
            name='task',
            field=models.ManyToManyField(related_name='bids', to='studentapp.task'),
        ),
    ]
