# Generated by Django 4.1.7 on 2023-03-01 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0008_alter_customuser_managers_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
    ]
