# Generated by Django 4.1.7 on 2023-03-08 21:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0010_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(max_length=65, unique=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+1-578954324'. Up to 15 digits allowed.", regex='^\\+?\\d{1,3}-\\d{6,15}$')]),
        ),
    ]
