# Generated by Django 4.1.7 on 2023-03-15 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Authapp', '0011_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
    ]
