# Generated by Django 4.1.7 on 2023-03-03 20:49

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Authapp', '0010_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('task_url', models.URLField(blank=True, null=True)),
                ('deadline_date', models.DateTimeField(verbose_name='Task Deadline Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('is_pending', models.BooleanField(default=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentapp.taskcategory')),
                ('stud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='Authapp.student')),
            ],
            options={
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('surname', models.CharField(blank=True, max_length=30, null=True)),
                ('lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('profile_picture', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='student_images')),
                ('location', models.CharField(blank=True, max_length=90)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stud_profile', to='Authapp.student')),
            ],
        ),
    ]
